### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by pauldendulk** [MattGerg/ShapefileSharp#1]
Hello there! I am looking for shapefile reader to port to mobile. Your project has an MIT shapefile so I was interested. It has a fair number of unit tests, but when I run them after a clean clone six fail. Does this mean the project got stalled halfway or am I doing something wrong?

**Comment by MattGerg** [comment]
The project stalled and was never completed.  I have meaning to come back
to this, but haven't had the time.

**Comment by pauldendulk** [comment]
ah clear, thanks for the quick reply!
